twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        versionFilePath: '%kernel.project_dir%/VERSION.md'

when@test:
    twig:
        strict_variables: true
