name: CI

# We only want Github actions runs on pull request from develop because of the free plan (500 Mo 2000 min/month)
on:
  #push:
  #  branches: [ feature/*, release/*, hotfix/* ]
  pull_request:
  #  branches: [ develop, main ]
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start containers
      run: docker compose up -d

    - name: Check containers status
      run: |
        docker ps -a
        docker logs job-search-web-1

    - name: Verify connected user in container web
      run: docker compose exec web whoami

    - name: Verify rights on /var/www/
      run: docker compose exec web ls -l /var/ | grep www

    - name: Install Composer dependencies
      run: docker compose exec web composer install --no-interaction --optimize-autoloader

    - name: Check Symfony requirements
      run: docker compose exec web symfony check:requirements
