name: Synchronize develop with main

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Merge main into develop
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge origin/main
          git push origin develop